name: 'Deploy Infrastructure'

on:
  push:
    branches:
      - main

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo "Hello World!" 

  DeployProd:
    name: Validate and Apply Terraform Script
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'https://gratian.tech'
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions/apply@v0.4.0
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
